<!-- process_current_sem.asp -->
<!-- #include file="dbconnect.asp" -->
<%
' Ensure the database connection is set up
Dim db, rsSub, rsStaff, sqlSub, sqlStaff, sqlInsert, lastSemId
Set db = OpenDatabaseConnection()

' Get form values (subject, staff, academic year, semester, and allocation type)
Dim subId, staffId, academicYear, semester, allocationType
subId = Request.Form("sub_id")
staffId = Request.Form("staff_id")
academicYear = Request.Form("academic_year")
semester = Request.Form("semester")
allocationType = Request.Form("allocation_type")

' Ensure all fields are provided
If subId = "" Or staffId = "" Or academicYear = "" Or semester = "" Or allocationType = "" Then
    Response.Write "<h3>All fields are required. Please fill in the missing details.</h3>"
    Response.End
End If

' Query to get subject name and staff name (optional if needed for confirmation)
sqlSub = "SELECT Sub_Name FROM Degree_Subject_table WHERE Sub_Id = '" & subId & "'"
Set rsSub = db.Execute(sqlSub)

sqlStaff = "SELECT Staff_Name FROM Staff_table WHERE Staff_Id = '" & staffId & "'"
Set rsStaff = db.Execute(sqlStaff)

' Check if subject and staff exist
If rsSub.EOF Or rsStaff.EOF Then
    Response.Write "<h3>Invalid subject or staff selected. Please check your selections.</h3>"
    rsSub.Close
    Set rsSub = Nothing
    rsStaff.Close
    Set rsStaff = Nothing
    db.Close
    Set db = Nothing
    Response.End
End If

' Insert into Current_sem table (Sem_Id is auto-generated by the database)
sqlInsert = "INSERT INTO Current_sem (AcademicYear, Semester, Sub_Id, Staff_Id, AllocationType) " & _
            "VALUES ('" & academicYear & "', '" & semester & "', '" & subId & "', '" & staffId & "', '" & allocationType & "')"

' Execute the insert query
db.Execute(sqlInsert)

' Get the last inserted Sem_Id (auto-generated)
sqlGetSemId = "SELECT @@IDENTITY AS Sem_Id"
Set rsSem = db.Execute(sqlGetSemId)

' Check if Sem_Id is retrieved successfully
If Not rsSem.EOF Then
    lastSemId = rsSem("Sem_Id")
    Response.Write "<h3>Semester allocation has been successfully recorded. The generated Sem_Id is: " & lastSemId & "</h3>"
Else
    Response.Write "<h3>Failed to retrieve Sem_Id. Please try again later.</h3>"
End If

' Clean up the database connection
rsSub.Close
Set rsSub = Nothing
rsStaff.Close
Set rsStaff = Nothing
rsSem.Close
Set rsSem = Nothing
db.Close
Set db = Nothing
%>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Semester Allocation Success</title>
    <style>
        body { font-family: Segoe UI, Tahoma, Geneva, Verdana, sans-serif; background-color: #f0f2f5; color: #333; margin: 0; padding: 0; }
        .container { max-width: 600px; margin: 100px auto; background: #fff; padding: 30px; border-radius: 12px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); text-align: center; }
        h3 { color: #1b263b; }
        .button-container { display: flex; justify-content: center; gap: 20px; flex-wrap: wrap; margin-top: 20px; }
        a.button { display: inline-block; padding: 10px 20px; background: #415a77; color: #fff; text-decoration: none; border-radius: 6px; font-weight: bold; transition: background-color 0.3s ease; }
        a.button:hover { background: #778da9; }
    </style>
</head>
<body>
    <div class="container">
        <h3>Semester allocation has been successfully recorded!</h3>
        <p>Generated Sem_Id: <strong><%= lastSemId %></strong></p>
        <div class="button-container">
            <a href="current_sem_form.html" class="button">Allocate Another Semester</a>
            <a href="admin_dashboard.asp" class="button">Back to Dashboard</a>
        </div>
    </div>
</body>
</html>
